# Build settings
markdown: kramdown
remote_theme: devops-kung-fu/dkfm

# Site settings
page.title: DevOps Kung Fu Mafia
site.name: DKFM
name: DKFM
description: "We make DevOps things that make DevOps things easier"
url: ""

github_username:  devops-kung-fu
twitter_username: _dkfm_

avatar: yes
avatar_img_path: "https://avatars.githubusercontent.com/u/77503959?s=400&u=af505101b668162da477d15bae5e03d22ef05262&v=4"

front_img: yes
front_img_path: "img/background.jpg"

favicon_img: yes
